import { Header } from '@/components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/Footer/Footer'

import { Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Билетопоиск',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className}`}>
        <Header/>
        <main className="content">
            {children}
        </main>
        <Footer/>
        
        <div id="dropdown"></div>    
        <div id="modal"></div>        
      </body>
    </html>
  )
}
